[build.environment]
  YARN_VERSION = "1.19.1"
  YARN_FLAGS = "--no-ignore-optional"
[[headers]]
    for = "/static/*"
        [headers.values]
        Cache-Control = "public, max-age=360000"
[[headers]]
    for = "/*"
        [headers.values]
        Access-Control-Allow-Origin = "*"
