backend:
  name: github
  repo: emmajgrimes/headforwards-website
#publish_mode: editorial_workflow

site_url: https://headforwards-website.netlify.com
display_url: https://headforwards.com
logo_url: https://headforwards-website.netlify.com/images/headforwards.black.png
show_preview_links: true

media_folder: static/uploads
public_folder: /uploads

collections:
  - name: "settings"
    label: "Site Settings"
    create: false
    files:
      - file: "src/data/main-menu.yml"
        label: "Main Menu"
        name: main-menu
        fields:
          - {label: "Title", name: title, widget: hidden, default: "main-menu"}
          - label: "Items"
            name: menu
            widget: list
            fields:
              - {label: "Label", name: linkText, widget: string}
              - {label: "Link", name: link, widget: relation, collection: design-pages, searchFields: [title], valueField: uuid, displayFields: [title]}
              - label: "Children"
                name: children
                widget: list
                fields:
                  - {label: "Label", name: linkText, widget: string}
                  - {label: "Link", name: link, widget: relation, collection: design-pages, searchFields: [title], valueField: uuid, displayFields: [title]}

      - file: "src/data/company-info.yml"
        label: "Company Information"
        name: company-info
        fields:
          - {label: "Title", name: title, widget: hidden, default: "company-info"}
          - {label: "Meta Title", name: metaTitle, widget: string}
          - {label: "Meta Description", name: metaDescription, widget: string}
          - {label: "Company Name", name: companyName, widget: string}
          - {label: "Email Address", name: email, widget: string}
          - {label: "Address", name: address, widget: text}
          - {label: "Phone Number", name: phone, widget: string}
          - {label: "Facebook URL",  name: facebookURL, widget: string, required: false}
          - {label: "Instagram URL",  name: instagramURL, widget: string, required: false}
          - {label: "Linkedin URL",  name: linkedInURL, widget: string, required: false}
          - {label: "Youtube URL",  name: youtubeURL, widget: string, required: false}
          - {label: "Twitter URL",  name: twitterURL, widget: string, required: false}

  - label: "Design Pages"
    label_singular: "Design Page"
    name: design-pages
    folder: "src/pages/design-pages"
    create: true
    slug: "{{slug}}"
    preview_path: "{{path}}/{{slug}}"
    widget: list
    identifier_field: title
    fields:
      - {label: "ID", name: uuid, widget: uuid, required: false, default: null}
      - {label: "Path", name: path, widget: hidden, default: "design-pages"}
      - {label: "Type", name: type, widget: hidden, default: "design"}
      - {label: "Page Title", name: title, widget: string}
      - {label: "Page Sub Title", name: text, widget: text, required: false}
      - {label: "Header Image", name:  image, widget: image, required: false}
      - label: "Page Components"
        name: components
        widget: list
        types:
          - label: "Hero Component"
            name: heroComponent
            widget: object
            fields:
              - {label: "Title", name: title, widget: string}
              - {label: "Split into two columns?", name: isTwoColumns, widget: boolean, default: false}
              - {label: "Copy", name: text, widget: markdown}

          - label: "Full Width Image"
            name: fullWidthImageComponent
            widget: object
            fields:
              - label: "Image"
                name: image
                widget: image

          - label: "Two Images"
            name: twoImageComponent
            widget: object
            fields:
              - {label: "Left Image", name: leftImage, widget: image}
              - {label: "Right Image", name: rightImage, widget: image}

          - label: "Quote"
            name: quoteComponent
            widget: object
            fields:
              - {label: "Quote", name: quote, widget: text}
              - {label: "Name", name: name, widget: string, required: false}
              - {label: "Job Title", name: jobTitle, widget: string, required: false}
              - {label: "Profile Picture", name: profilePic, widget: image, required: false}

          - label: "Image, Copy Columns"
            name: imageCopyColumnsComponent
            widget: object
            fields:
              - {label: "Title", name: title, widget: string}
              - {label: "Image", name: image, widget: image}
              - {label: "Image on the right?", name: isRightImage, widget: boolean, default: false}
              - {label: "Copy", name: text, widget: text}
              - {label: "Link Text", name: linkText, widget: string, required: false}
              - {label: "Link", name: link, widget: relation, collection: design-pages, searchFields: [title], valueField: uuid, displayFields: [title], required: false}

          - label: "Postit, Copy Columns"
            name: postitCopyColumnsComponent
            widget: object
            fields:
              - {label: "Title", name: title, widget: string}
              - {label: "Postit on the right?", name: isRightImage, widget: boolean, default: false}
              - {label: "Copy", name: text, widget: text}
              - {label: "Link Text", name: linkText, widget: string, required: false}
              - {label: "Link", name: link, widget: relation, collection: design-pages, searchFields: [title], valueField: uuid, displayFields: [title], required: false}

          - label: "Article Columns"
            name: articleColumnsComponent
            widget: object
            fields:
              - {label: "Component Title", name: title, widget: string, required: false}
              - label: "Articles"
                name: articles
                widget: list
                fields:
                  - {label: "Title", name: title, widget: string}
                  - {label: "Image", name: image, widget: image}
                  - {label: "Copy", name: text, widget: text}
                  - {label: "Link Text", name: linkText, widget: string, required: false}
                  - {label: "Link", name: link, widget: relation, collection: design-pages, searchFields: [title], valueField: uuid, displayFields: [title], required: false}

          - label: "Blog Post Columns"
            name: blogPostColumnsComponent
            widget: object
            fields:
              - {label: "Component Title", name: title, widget: string}
              - label: "Blog Posts"
                name: articles
                widget: list
                fields:
                  - {label: "Title", name: title, widget: string}
                  - {label: "Image", name:  image, widget: image}
                  - {label: "Link Text", name: linkText, widget: string, required: false}
                  - {label: "Link", name: link, widget: relation, collection: design-pages, searchFields: [title], valueField: uuid, displayFields: [title], required: false}

          - label: "Content Slider"
            name: "contentSliderComponent"
            widget: object
            fields:
              - {label: "Component Title", name: title, widget: string}
              - label: "Slides"
                name: "articles"
                widget: list
                fields:
                  - {label: "Title", name: title, widget: string}
                  - {label: "Image", name: image, widget: image}
                  - {label: "Copy", name: text, widget: text}
                  - {label: "Link Text", name: linkText, widget: string, required: false}
                  - {label: "Link", name: link, widget: relation, collection: design-pages, searchFields: [title], valueField: uuid, displayFields: [title], required: false}



